// Generated by gencpp from file ltme_node/QueryFirmwareVersion.msg
// DO NOT EDIT!


#ifndef LTME_NODE_MESSAGE_QUERYFIRMWAREVERSION_H
#define LTME_NODE_MESSAGE_QUERYFIRMWAREVERSION_H

#include <ros/service_traits.h>


#include <ltme_node/QueryFirmwareVersionRequest.h>
#include <ltme_node/QueryFirmwareVersionResponse.h>


namespace ltme_node
{

struct QueryFirmwareVersion
{

typedef QueryFirmwareVersionRequest Request;
typedef QueryFirmwareVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryFirmwareVersion
} // namespace ltme_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ltme_node::QueryFirmwareVersion > {
  static const char* value()
  {
    return "968367e081bb6dba33b3daf3e01dab62";
  }

  static const char* value(const ::ltme_node::QueryFirmwareVersion&) { return value(); }
};

template<>
struct DataType< ::ltme_node::QueryFirmwareVersion > {
  static const char* value()
  {
    return "ltme_node/QueryFirmwareVersion";
  }

  static const char* value(const ::ltme_node::QueryFirmwareVersion&) { return value(); }
};


// service_traits::MD5Sum< ::ltme_node::QueryFirmwareVersionRequest> should match
// service_traits::MD5Sum< ::ltme_node::QueryFirmwareVersion >
template<>
struct MD5Sum< ::ltme_node::QueryFirmwareVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ltme_node::QueryFirmwareVersion >::value();
  }
  static const char* value(const ::ltme_node::QueryFirmwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltme_node::QueryFirmwareVersionRequest> should match
// service_traits::DataType< ::ltme_node::QueryFirmwareVersion >
template<>
struct DataType< ::ltme_node::QueryFirmwareVersionRequest>
{
  static const char* value()
  {
    return DataType< ::ltme_node::QueryFirmwareVersion >::value();
  }
  static const char* value(const ::ltme_node::QueryFirmwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ltme_node::QueryFirmwareVersionResponse> should match
// service_traits::MD5Sum< ::ltme_node::QueryFirmwareVersion >
template<>
struct MD5Sum< ::ltme_node::QueryFirmwareVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ltme_node::QueryFirmwareVersion >::value();
  }
  static const char* value(const ::ltme_node::QueryFirmwareVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltme_node::QueryFirmwareVersionResponse> should match
// service_traits::DataType< ::ltme_node::QueryFirmwareVersion >
template<>
struct DataType< ::ltme_node::QueryFirmwareVersionResponse>
{
  static const char* value()
  {
    return DataType< ::ltme_node::QueryFirmwareVersion >::value();
  }
  static const char* value(const ::ltme_node::QueryFirmwareVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LTME_NODE_MESSAGE_QUERYFIRMWAREVERSION_H
