// Generated by gencpp from file ltme_node/QuerySerial.msg
// DO NOT EDIT!


#ifndef LTME_NODE_MESSAGE_QUERYSERIAL_H
#define LTME_NODE_MESSAGE_QUERYSERIAL_H

#include <ros/service_traits.h>


#include <ltme_node/QuerySerialRequest.h>
#include <ltme_node/QuerySerialResponse.h>


namespace ltme_node
{

struct QuerySerial
{

typedef QuerySerialRequest Request;
typedef QuerySerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QuerySerial
} // namespace ltme_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ltme_node::QuerySerial > {
  static const char* value()
  {
    return "fca40cf463282a80db4e2037c8a61741";
  }

  static const char* value(const ::ltme_node::QuerySerial&) { return value(); }
};

template<>
struct DataType< ::ltme_node::QuerySerial > {
  static const char* value()
  {
    return "ltme_node/QuerySerial";
  }

  static const char* value(const ::ltme_node::QuerySerial&) { return value(); }
};


// service_traits::MD5Sum< ::ltme_node::QuerySerialRequest> should match
// service_traits::MD5Sum< ::ltme_node::QuerySerial >
template<>
struct MD5Sum< ::ltme_node::QuerySerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ltme_node::QuerySerial >::value();
  }
  static const char* value(const ::ltme_node::QuerySerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltme_node::QuerySerialRequest> should match
// service_traits::DataType< ::ltme_node::QuerySerial >
template<>
struct DataType< ::ltme_node::QuerySerialRequest>
{
  static const char* value()
  {
    return DataType< ::ltme_node::QuerySerial >::value();
  }
  static const char* value(const ::ltme_node::QuerySerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ltme_node::QuerySerialResponse> should match
// service_traits::MD5Sum< ::ltme_node::QuerySerial >
template<>
struct MD5Sum< ::ltme_node::QuerySerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ltme_node::QuerySerial >::value();
  }
  static const char* value(const ::ltme_node::QuerySerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltme_node::QuerySerialResponse> should match
// service_traits::DataType< ::ltme_node::QuerySerial >
template<>
struct DataType< ::ltme_node::QuerySerialResponse>
{
  static const char* value()
  {
    return DataType< ::ltme_node::QuerySerial >::value();
  }
  static const char* value(const ::ltme_node::QuerySerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LTME_NODE_MESSAGE_QUERYSERIAL_H
