// Generated by gencpp from file ltme_node/QuerySerialResponse.msg
// DO NOT EDIT!


#ifndef LTME_NODE_MESSAGE_QUERYSERIALRESPONSE_H
#define LTME_NODE_MESSAGE_QUERYSERIALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ltme_node
{
template <class ContainerAllocator>
struct QuerySerialResponse_
{
  typedef QuerySerialResponse_<ContainerAllocator> Type;

  QuerySerialResponse_()
    : serial()  {
    }
  QuerySerialResponse_(const ContainerAllocator& _alloc)
    : serial(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _serial_type;
  _serial_type serial;





  typedef boost::shared_ptr< ::ltme_node::QuerySerialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltme_node::QuerySerialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QuerySerialResponse_

typedef ::ltme_node::QuerySerialResponse_<std::allocator<void> > QuerySerialResponse;

typedef boost::shared_ptr< ::ltme_node::QuerySerialResponse > QuerySerialResponsePtr;
typedef boost::shared_ptr< ::ltme_node::QuerySerialResponse const> QuerySerialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltme_node::QuerySerialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltme_node::QuerySerialResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QuerySerialResponse_<ContainerAllocator2> & rhs)
{
  return lhs.serial == rhs.serial;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltme_node::QuerySerialResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QuerySerialResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltme_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QuerySerialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QuerySerialResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QuerySerialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fca40cf463282a80db4e2037c8a61741";
  }

  static const char* value(const ::ltme_node::QuerySerialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfca40cf463282a80ULL;
  static const uint64_t static_value2 = 0xdb4e2037c8a61741ULL;
};

template<class ContainerAllocator>
struct DataType< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltme_node/QuerySerialResponse";
  }

  static const char* value(const ::ltme_node::QuerySerialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string serial\n"
"\n"
;
  }

  static const char* value(const ::ltme_node::QuerySerialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuerySerialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltme_node::QuerySerialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltme_node::QuerySerialResponse_<ContainerAllocator>& v)
  {
    s << indent << "serial: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.serial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTME_NODE_MESSAGE_QUERYSERIALRESPONSE_H
