// Generated by gencpp from file ltme_node/QueryHardwareVersionResponse.msg
// DO NOT EDIT!


#ifndef LTME_NODE_MESSAGE_QUERYHARDWAREVERSIONRESPONSE_H
#define LTME_NODE_MESSAGE_QUERYHARDWAREVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ltme_node
{
template <class ContainerAllocator>
struct QueryHardwareVersionResponse_
{
  typedef QueryHardwareVersionResponse_<ContainerAllocator> Type;

  QueryHardwareVersionResponse_()
    : hardware_version()  {
    }
  QueryHardwareVersionResponse_(const ContainerAllocator& _alloc)
    : hardware_version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _hardware_version_type;
  _hardware_version_type hardware_version;





  typedef boost::shared_ptr< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryHardwareVersionResponse_

typedef ::ltme_node::QueryHardwareVersionResponse_<std::allocator<void> > QueryHardwareVersionResponse;

typedef boost::shared_ptr< ::ltme_node::QueryHardwareVersionResponse > QueryHardwareVersionResponsePtr;
typedef boost::shared_ptr< ::ltme_node::QueryHardwareVersionResponse const> QueryHardwareVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.hardware_version == rhs.hardware_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltme_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77f2d4a0768554de8b833ceceda9c80a";
  }

  static const char* value(const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77f2d4a0768554deULL;
  static const uint64_t static_value2 = 0x8b833ceceda9c80aULL;
};

template<class ContainerAllocator>
struct DataType< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltme_node/QueryHardwareVersionResponse";
  }

  static const char* value(const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string hardware_version\n"
"\n"
;
  }

  static const char* value(const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hardware_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryHardwareVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltme_node::QueryHardwareVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "hardware_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.hardware_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTME_NODE_MESSAGE_QUERYHARDWAREVERSIONRESPONSE_H
