// Generated by gencpp from file ltme_node/QueryFirmwareVersionResponse.msg
// DO NOT EDIT!


#ifndef LTME_NODE_MESSAGE_QUERYFIRMWAREVERSIONRESPONSE_H
#define LTME_NODE_MESSAGE_QUERYFIRMWAREVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ltme_node
{
template <class ContainerAllocator>
struct QueryFirmwareVersionResponse_
{
  typedef QueryFirmwareVersionResponse_<ContainerAllocator> Type;

  QueryFirmwareVersionResponse_()
    : firmware_version()  {
    }
  QueryFirmwareVersionResponse_(const ContainerAllocator& _alloc)
    : firmware_version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _firmware_version_type;
  _firmware_version_type firmware_version;





  typedef boost::shared_ptr< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryFirmwareVersionResponse_

typedef ::ltme_node::QueryFirmwareVersionResponse_<std::allocator<void> > QueryFirmwareVersionResponse;

typedef boost::shared_ptr< ::ltme_node::QueryFirmwareVersionResponse > QueryFirmwareVersionResponsePtr;
typedef boost::shared_ptr< ::ltme_node::QueryFirmwareVersionResponse const> QueryFirmwareVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.firmware_version == rhs.firmware_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator1> & lhs, const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltme_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "968367e081bb6dba33b3daf3e01dab62";
  }

  static const char* value(const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x968367e081bb6dbaULL;
  static const uint64_t static_value2 = 0x33b3daf3e01dab62ULL;
};

template<class ContainerAllocator>
struct DataType< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltme_node/QueryFirmwareVersionResponse";
  }

  static const char* value(const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string firmware_version\n"
"\n"
;
  }

  static const char* value(const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.firmware_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryFirmwareVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltme_node::QueryFirmwareVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "firmware_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.firmware_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTME_NODE_MESSAGE_QUERYFIRMWAREVERSIONRESPONSE_H
