// Generated by gencpp from file hins_he_driver/hins_srv.msg
// DO NOT EDIT!


#ifndef HINS_HE_DRIVER_MESSAGE_HINS_SRV_H
#define HINS_HE_DRIVER_MESSAGE_HINS_SRV_H

#include <ros/service_traits.h>


#include <hins_he_driver/hins_srvRequest.h>
#include <hins_he_driver/hins_srvResponse.h>


namespace hins_he_driver
{

struct hins_srv
{

typedef hins_srvRequest Request;
typedef hins_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hins_srv
} // namespace hins_he_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hins_he_driver::hins_srv > {
  static const char* value()
  {
    return "1b7a8b465a26f7d507ff8e5984967a01";
  }

  static const char* value(const ::hins_he_driver::hins_srv&) { return value(); }
};

template<>
struct DataType< ::hins_he_driver::hins_srv > {
  static const char* value()
  {
    return "hins_he_driver/hins_srv";
  }

  static const char* value(const ::hins_he_driver::hins_srv&) { return value(); }
};


// service_traits::MD5Sum< ::hins_he_driver::hins_srvRequest> should match
// service_traits::MD5Sum< ::hins_he_driver::hins_srv >
template<>
struct MD5Sum< ::hins_he_driver::hins_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hins_he_driver::hins_srv >::value();
  }
  static const char* value(const ::hins_he_driver::hins_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hins_he_driver::hins_srvRequest> should match
// service_traits::DataType< ::hins_he_driver::hins_srv >
template<>
struct DataType< ::hins_he_driver::hins_srvRequest>
{
  static const char* value()
  {
    return DataType< ::hins_he_driver::hins_srv >::value();
  }
  static const char* value(const ::hins_he_driver::hins_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hins_he_driver::hins_srvResponse> should match
// service_traits::MD5Sum< ::hins_he_driver::hins_srv >
template<>
struct MD5Sum< ::hins_he_driver::hins_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hins_he_driver::hins_srv >::value();
  }
  static const char* value(const ::hins_he_driver::hins_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hins_he_driver::hins_srvResponse> should match
// service_traits::DataType< ::hins_he_driver::hins_srv >
template<>
struct DataType< ::hins_he_driver::hins_srvResponse>
{
  static const char* value()
  {
    return DataType< ::hins_he_driver::hins_srv >::value();
  }
  static const char* value(const ::hins_he_driver::hins_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HINS_HE_DRIVER_MESSAGE_HINS_SRV_H
