(cl:defpackage ltme_node-srv
  (:use )
  (:export
   "QUERYFIRMWAREVERSION"
   "<QUERYFIRMWAREVERSION-REQUEST>"
   "QUERYFIRMWAREVERSION-REQUEST"
   "<QUERYFIRMWAREVERSION-RESPONSE>"
   "QUERYFIRMWAREVERSION-RESPONSE"
   "QUERYHARDWAREVERSION"
   "<QUERYHARDWAREVERSION-REQUEST>"
   "QUERYHARDWAREVERSION-REQUEST"
   "<QUERYHARDWAREVERSION-RESPONSE>"
   "QUERYHARDWAREVERSION-RESPONSE"
   "QUERYSERIAL"
   "<QUERYSERIAL-REQUEST>"
   "QUERYSERIAL-REQUEST"
   "<QUERYSERIAL-RESPONSE>"
   "QUERYSERIAL-RESPONSE"
  ))

